//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public System.Guid ObjId { get; set; }
        public string IdNo { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
    }

	public partial class ExcersizeModel
	{
		public string Chapter { get; set; }
	}
}
